import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/globals.css";
import NavigationBar from "@/customComponents/NavigationBar";
import Footer from "@/customComponents/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Real Estate",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col bg-gray-50`}
      >
        {/* Navigation */}
        <div className="navigation">
          <NavigationBar />
        </div>
        {/* Body */}
        <div className="body grow">
        {children}
        </div>
        {/* Footer */}
        <div className="footer">
          <Footer />
        </div>
      </body>
    </html>
  );
}
